language: node_js
cache: npm
node_js:
  - node
  - "12"
branches:
  only:
      - gh-pages
      - /.*/
      - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

deploy:
  provider: npm
  email: 13450737557@163.com
  api_key: $NPM_API_TOKEN
  access: public
  edge: true
  tag: beta
  on:
    tags: true
    branch: main
